services:
  web:
    build: .
    restart: "no"
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fintrack
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./:/app
    command: python app.py

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRSS_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: